// Product units constant
export const units = [
  { id: 1, code: "pc", name: "Piece", type: "count" },
  { id: 2, code: "unit", name: "Unit", type: "count" },
  { id: 3, code: "set", name: "Set", type: "count" },
  { id: 4, code: "pair", name: "Pair", type: "count" },
  { id: 5, code: "dozen", name: "Dozen", type: "count" },
  { id: 10, code: "mg", name: "Milligram", type: "weight" },
  { id: 11, code: "g", name: "Gram", type: "weight" },
  { id: 12, code: "kg", name: "Kilogram", type: "weight" },
  { id: 13, code: "ton", name: "Metric Ton", type: "weight" },
  { id: 14, code: "lb", name: "Pound", type: "weight" },
  { id: 20, code: "ml", name: "Milliliter", type: "volume" },
  { id: 21, code: "l", name: "Liter", type: "volume" },
  { id: 22, code: "cc", name: "Cubic Centimeter", type: "volume" },
  { id: 23, code: "gallon", name: "Gallon", type: "volume" },
  { id: 30, code: "mm", name: "Millimeter", type: "length" },
  { id: 31, code: "cm", name: "Centimeter", type: "length" },
  { id: 32, code: "m", name: "Meter", type: "length" },
  { id: 33, code: "ft", name: "Foot", type: "length" },
  { id: 40, code: "sqm", name: "Square Meter", type: "area" },
  { id: 41, code: "sqft", name: "Square Foot", type: "area" },
  { id: 50, code: "box", name: "Box", type: "packaging" },
  { id: 51, code: "carton", name: "Carton", type: "packaging" },
  { id: 52, code: "packet", name: "Packet", type: "packaging" },
  { id: 53, code: "bag", name: "Bag", type: "packaging" },
  { id: 54, code: "bottle", name: "Bottle", type: "packaging" },
  { id: 60, code: "hour", name: "Hour", type: "service" },
  { id: 61, code: "day", name: "Day", type: "service" },
  { id: 62, code: "month", name: "Month", type: "service" },
  { id: 63, code: "year", name: "Year", type: "service" },
];
